name: Java CI - Specific Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Run Specific Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' 
          java-version: '11'
          cache: maven  
          
      - name: Run Specific Test
        run: mvn test -Dtest=org.telegram.telegrambots.meta.api.methods.send.TestSendMessage